name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v6

      - name: Set up JVM
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Test
        run: sh ./gradlew check --info
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v6

      - name: Set up JVM
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Publish to Maven Central
        run: ./gradlew publish --info
        env:
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ github.event.release.tag_name }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.central_username }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.central_password }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.signing_key }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.signing_key_password }}